Fix AttributeError: 'module' object has no attribute 'dumps' on Python 2
Fixes https://bitbucket.org/sirex/django-sboard/issues/1/attributeerror-module-object-has-no
and therefore https://github.com/ManoSeimas/manoseimas.lt/issues/78